name: Latest blog post workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update latest blog posts in README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://brennerm.github.io/atom.xml"